### ISSUE TITLE
Dumping Files using the docker version - Vol3

### ISSUE THREAD

**Issue by e1kfL0ck** [Abyss-W4tcher/ab4yss-tools#2]
Hello, 
I would like first to thanks you for this script, very usefull !

I want to dump a file using the docker version of volatility3. 
I serach a bit accross the Internet but didn't found the anwser. 

Can someone help me ? Thanks !

**Comment by Abyss-W4tcher** [comment]
Hi, you can try : https://book.hacktricks.xyz/generic-methodologies-and-resources/basic-forensic-methodology/memory-dump-analysis/volatility-cheatsheet#scan-dump
